[phases.setup]
nixPkgs = [
  "php82",
  "composer",
  "php82Packages.pdo",
  "php82Packages.mysql",  # jika pakai MySQL
  "php82Packages.mbstring",
  "php82Packages.tokenizer",
  "php82Packages.openssl",
  "php82Packages.curl"
]

[phases.build]
cmds = [
  "composer install",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.start]
cmds = ["php artisan serve --host=0.0.0.0 --port=8080"]
